language: csharp
solution: SharpC2.sln
mono: none
dotnet: 5.0.2
script:
 - dotnet restore
 - dotnet build
 - dotnet test ./Tests/API.IntegrationTests --filter HandlerTests
 - dotnet test ./Tests/API.IntegrationTests --filter PayloadTests
 - dotnet test ./Tests/TeamServer.UnitTests